# Generated by Django 5.1.4 on 2025-01-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_courses", "0004_remove_unit_course_lesson"),
        ("users", "0003_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="unit",
        ),
        migrations.AddField(
            model_name="payment",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="online_courses.lesson",
                verbose_name="Оплаченный урок",
            ),
        ),
    ]
