# Generated by Django 5.1.4 on 2025-01-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                blank=True,
                help_text="complete(оплачен)/expired(не действителен)/open(ожидает оплаты)",
                max_length=250,
                null=True,
                verbose_name="Статус платежа",
            ),
        ),
    ]
