# Generated by Django 5.1.4 on 2025-01-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Является активным пользователем"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Последний вход на сайт"),
        ),
    ]
