# Generated by Django 5.1.4 on 2025-01-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_is_active_alter_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateField(auto_now_add=True, null=True, verbose_name="Последний вход на сайт"),
        ),
    ]
