# Generated by Django 5.1.4 on 2025-01-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateField(auto_now_add=True, null=True, verbose_name="Последняя активность"),
        ),
    ]
