# Generated by Django 5.1.4 on 2025-01-06 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="Название курса")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="course_img/", verbose_name="Превью (картинка)"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание курса")),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название урока", max_length=200, unique=True, verbose_name="Название урока"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание урока")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="unit_img/", verbose_name="Превью (картинка)"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.SET,
                        to="online_courses.course",
                        verbose_name="Название курса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
