# Generated by Django 5.1.4 on 2025-01-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="video",
            field=models.TextField(blank=True, null=True, verbose_name="Ссылка на видео"),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(max_length=200, unique=True, verbose_name="Название урока"),
        ),
    ]
