# Generated by Django 5.1.4 on 2025-01-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_courses", "0002_unit_video_alter_unit_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="video",
            field=models.CharField(blank=True, null=True, verbose_name="Ссылка на видео"),
        ),
    ]
