# Generated by Django 5.1.4 on 2025-01-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_courses", "0003_alter_unit_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="course",
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True, verbose_name="Название урока")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание урока")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="unit_img/", verbose_name="Превью (картинка)"),
                ),
                ("video", models.CharField(blank=True, null=True, verbose_name="Ссылка на видео")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.SET,
                        related_name="lesson_set",
                        to="online_courses.course",
                        verbose_name="Название курса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
