# Generated by Django 5.1.4 on 2025-01-07 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("online_courses", "0004_remove_unit_course_lesson"),
        ("users", "0004_remove_payment_unit_payment_lesson"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Unit",
        ),
    ]
