# Generated by Django 5.1.4 on 2025-01-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_courses", "0007_follow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка на видео"),
        ),
    ]
